services:
 mysql:
  image: mysql:8.0
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: admin
   MYSQL_DATABASE: site
   MYSQL_USER: admin
   MYSQL_PASSWORD: admin
   MYSQL_ROOT_HOST: '%'

 wordpress:
  image: wordpress:latest
  depends_on:
   - mysql
  links:
   - mysql
  ports:
   - 8000:80
  environment:
   WORDPRESS_DB_HOST: mysql:3306
   WORDPRESS_DB_USER: admin
   WORDPRESS_DB_PASSWORD: admin
   WORDPRESS_DB_NAME: site
   WORDPRESS_DEBUG: 1
  volumes:
   - './wordpress:/var/www/html'

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  depends_on:
   - mysql
  links:
   - mysql
  ports:
   - 8181:80
  environment:
   MYSQL_USERNAME: admin
   MYSQL_ROOT_PASSWORD: admin
   PMA_HOST: mysql
